#ifndef PROTOCOLGRAPH_GLOBAL_H
#define PROTOCOLGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOLGRAPH_LIBRARY)
#  define PROTOCOLGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOLGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOLGRAPH_GLOBAL_H
