#ifndef PROTOCOLGRAPH_GLOBAL_H
#define PROTOCOLGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOLGRAPH_LIBRARY)
#  define PROTOCOLGRAPH_EXPORT Q_DECL_EXPORT
#  define APPLYLIGHT_EXPORT Q_DECL_EXPORT
#  define APPLYTEMPERATURE_EXPORT Q_DECL_EXPORT
#  define DIVERGENODE_EXPORT Q_DECL_EXPORT
#  define LOOPNODE_EXPORT Q_DECL_EXPORT
#  define ASSIGNATIONOPERATION_EXPORT Q_DECL_EXPORT
#  define GETVOLUME_EXPORT Q_DECL_EXPORT
#  define LOADCONTAINEROPERATION_EXPORT Q_DECL_EXPORT
#  define MEASUREOD_EXPORT Q_DECL_EXPORT
#  define MIX_EXPORT Q_DECL_EXPORT
#  define CONDITIONEDGE_EXPORT Q_DECL_EXPORT
#  define SETCONTINOUSFLOW_EXPORT Q_DECL_EXPORT
#  define SETTIMESTEP_EXPORT Q_DECL_EXPORT
#  define STIR_EXPORT Q_DECL_EXPORT
#  define TIMESTEP_EXPORT Q_DECL_EXPORT
#  define TRANSFER_EXPORT Q_DECL_EXPORT
#  define VARIABLETABLE_EXPORT Q_DECL_EXPORT
#  define ARITHMETICOPERATION_EXPORT Q_DECL_EXPORT
#  define MATHEMATICOPERABLE_EXPORT Q_DECL_EXPORT
#  define CONSTANTNUMBER_EXPORT Q_DECL_EXPORT
#  define UNARYOPERATION_EXPORT Q_DECL_EXPORT
#  define VARIABLEENTRY_EXPORT Q_DECL_EXPORT
#  define COMPARISONOPERABLE_EXPORT Q_DECL_EXPORT
#  define BOOLEANCOMPARISON_EXPORT Q_DECL_EXPORT
#  define SIMPLECOMPARISON_EXPORT Q_DECL_EXPORT
#  define TAUTOLOGY_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOLGRAPH_EXPORT Q_DECL_IMPORT
#  define APPLYLIGHT_EXPORT Q_DECL_IMPORT
#  define APPLYTEMPERATURE_EXPORT Q_DECL_IMPORT
#  define DIVERGENODE_EXPORT Q_DECL_IMPORT
#  define LOOPNODE_EXPORT Q_DECL_IMPORT
#  define ASSIGNATIONOPERATION_EXPORT Q_DECL_IMPORT
#  define GETVOLUME_EXPORT Q_DECL_IMPORT
#  define LOADCONTAINEROPERATION_EXPORT Q_DECL_IMPORT
#  define MEASUREOD_EXPORT Q_DECL_IMPORT
#  define MIX_EXPORT Q_DECL_IMPORT
#  define CONDITIONEDGE_EXPORT Q_DECL_IMPORT
#  define SETCONTINOUSFLOW_EXPORT Q_DECL_IMPORT
#  define SETTIMESTEP_EXPORT Q_DECL_IMPORT
#  define STIR_EXPORT Q_DECL_IMPORT
#  define TIMESTEP_EXPORT Q_DECL_IMPORT
#  define TRANSFER_EXPORT Q_DECL_IMPORT
#  define VARIABLETABLE_EXPORT Q_DECL_IMPORT
#  define ARITHMETICOPERATION_EXPORT Q_DECL_IMPORT
#  define MATHEMATICOPERABLE_EXPORT Q_DECL_IMPORT
#  define CONSTANTNUMBER_EXPORT Q_DECL_IMPORT
#  define UNARYOPERATION_EXPORT Q_DECL_IMPORT
#  define VARIABLEENTRY_EXPORT Q_DECL_IMPORT
#  define COMPARISONOPERABLE_EXPORT Q_DECL_IMPORT
#  define BOOLEANCOMPARISON_EXPORT Q_DECL_IMPORT
#  define SIMPLECOMPARISON_EXPORT Q_DECL_IMPORT
#  define TAUTOLOGY_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOLGRAPH_GLOBAL_H
